function g = growthterms_c2_withgrowthfactors(c1,c2,q1,q2,PO2,Pm,alpha21,...
    alpha22,beta,beta_hat,gamma2,cmax,hyaloid)
% g = growthterms_c2_withgrowthfactors(c1,c2,q1,q2,PO2,Pm,alpha21,...
%     alpha22,beta,beta_hat,gamma2,cmax,hyaloid)
%
% growth terms just IPAs (c2): g2

hyaloid = hyaloid(1:length(c1));
choroid = PO2./(Pm+PO2);

g = ( alpha21*(hyaloid + choroid) + alpha22*q1 ).*c2.*(1 - (c1+c2)/cmax) ...
    + beta*(hyaloid + choroid + q2).*c1 ...
    + (beta_hat/cmax)*c1.*c2 ...
    - gamma2.*c2;