function g = growthterms_c1_withgrowthfactors(c1,c2,q1,q2,PO2,Pm,alpha11,...
    alpha12,beta,beta_hat,gamma1,cmax,hyaloid)
% g = growthterms_c1_withgrowthfactors(c1,c2,q1,q2,PO2,Pm,alpha11,...
%     alpha12,beta,beta_hat,gamma1,cmax,hyaloid)
%
% growth terms just APCs (c1): g1

hyaloid = hyaloid(1:length(c1));
choroid = PO2./(Pm+PO2);

g = ( alpha11*(hyaloid + choroid) + alpha12*q1 ).*c1.*(1 - (c1+c2)/cmax) ...
    - beta*(hyaloid + choroid + q2).*c1 ...
    - (beta_hat/cmax)*c1.*c2 ...
    - gamma1*c1;