function g = growthterms_c1_withgrowthfactors(c1,c2,q1,q2,PO2,Pm,alpha1,...
    beta,beta_hat,gamma1,cmax,hyaloid)
% g = growthterms_c1(c1,c2,q1,q2,PO2,Pm,alpha1,beta,beta_hat,gamma1,cmax,hyaloid)
%
% growth terms

hyaloid = hyaloid(1:length(c1));
choroid = PO2./(Pm+PO2);

g = alpha1*(hyaloid + choroid + q1).*c1.*(1 - (c1+c2)/cmax) ...
    - beta*(hyaloid + choroid + q2).*c1 ...
    - (beta_hat/cmax)*c1.*c2 ...
    - gamma1*c1;