function Tpp = Tsecderivative(c,kappa,cmin,rbar)

Tpp = kappa/(4*sqrt(c)*(c^2 + cmin^2)^3*sqrt(pi)) * ...
    ((3*c^4 - 26*c^2*cmin^2 + 3*cmin^4 ...
    + 24*c^(5/2)*cmin^2*sqrt(pi)*rbar - 8*sqrt(c)*cmin^4*sqrt(pi)*rbar));